### PR TITLE
Use Finlandica font in drawer item

### PR DESCRIPTION
**Pull request by joni-**
Also hide the background color for active item

### CODE REVIEW

**Comment by akx** [comment]
Still seeing Roboto, here... Hmm.

screen shot 2018-02-14 at 9 46 58

**Comment by joni-** [comment]
Weird, was able to reproduce. Seems to work in iOS but not in Android.

**Comment by joni-** [comment]
I think I got it working now. Android required `fontWeight` to be set `normal` to display the font correctly.

**Comment by akx** [comment]
Looks good now, yup! 🎉 

screen shot 2018-02-16 at 10 30 32

**Pull request merged**
